-- Update social trait categories to be more creature-appropriate
-- Replaces: Persuasion → Friendliness, Team Player → Playfulness, Wisdom → Curiosity

-- ============================================================================
-- STEP 1: Update existing categories
-- ============================================================================

-- Replace Persuasion (id=1) with Friendliness
UPDATE dim_social_trait_category
SET
  category_name = 'Friendliness',
  description = 'How warm and welcoming they are, approachable and sociable',
  icon = '😊'
WHERE category_name = 'Persuasion';

-- Replace Team Player (id=2) with Playfulness
UPDATE dim_social_trait_category
SET
  category_name = 'Playfulness',
  description = 'Love of games and fun activities, enjoys playing around',
  icon = '🎮'
WHERE category_name = 'Team Player';

-- Replace Wisdom (id=8) with Curiosity
UPDATE dim_social_trait_category
SET
  category_name = 'Curiosity',
  description = 'Eager to explore and learn, adventurous and inquisitive',
  icon = '🔍'
WHERE category_name = 'Wisdom';

-- Keep but refine descriptions for existing categories:
UPDATE dim_social_trait_category
SET description = 'How imaginative and artistic they are, thinks outside the box'
WHERE category_name = 'Creativity';

UPDATE dim_social_trait_category
SET description = 'Understanding and caring, emotionally intelligent and kind'
WHERE category_name = 'Empathy';

UPDATE dim_social_trait_category
SET description = 'How active and excited they are, enthusiasm and vitality'
WHERE category_name = 'Energy Level';

UPDATE dim_social_trait_category
SET description = 'Self-assured and bold, confident in themselves and their choices'
WHERE category_name = 'Confidence';

UPDATE dim_social_trait_category
SET description = 'Funny and entertaining, brings joy and laughter to others'
WHERE category_name = 'Humor';

-- ============================================================================
-- STEP 2: Regenerate scores for updated categories
-- ============================================================================

-- Delete existing scores for the 3 changed categories
DELETE FROM creature_social_traits
WHERE trait_category_id IN (
  SELECT id FROM dim_social_trait_category
  WHERE category_name IN ('Friendliness', 'Playfulness', 'Curiosity')
);

-- Note: New scores will be generated by the migration script
-- This keeps the SQL clean and allows the script to use proper random distribution

-- ============================================================================
-- STEP 3: Add comment noting the change
-- ============================================================================

COMMENT ON TABLE dim_social_trait_category IS 'The 8 social trait categories for Top Trumps style interactions - Updated to be more creature-appropriate (Friendliness, Playfulness, Curiosity)';
